added memory_d>1 functionality
nengo/keras-lmu pull request #40
Opened 2021-04-28 07:25 UTC by NarsimhaChilkuri

LMUFFT should now be able to handle memory_d > 1, i.e, the input need not be projected down to a scalar before being fed into the delay layer.

2021-04-28 12:27 UTC, arvoelke commented
Awesome! This will be very useful to have. The check inside of LMU that delegates to this implementation can also have the `memory_d` check removed. Would be good to have a unit test too. Could probably extend one of the ones already in here.

2021-04-28 13:21 UTC, tbekolay commented
Thanks @NarsimhaChilkuri! Can you sign the CAA by adding yourself to [this page](https://github.com/nengo/nengo.github.io/blob/master/people.md)?

2021-06-15 15:25 UTC, hunse approved these changes
I've got this fixed up and ready to go.

I had to add a `has_input_kernel` option to allow turning off the input kernel in `LMUFFT.delay_layer` so that `test_layer_vs_cell` can pass (otherwise there was a mismatch in the number of weights). This is a feature that I figured we want anyway (a lot of our recent work uses LMUs with no dense encoding layer).

I combined the test that @NarsimhaChilkuri added into our existing `test_fft`. The main difference is that it tests a few more cases. Otherwise just added a few comments and a changelog entry.

It looks like TravisCI doesn't run when it's an outside contributor branch, so I made a copy of this at `origin/multi-dim-memory`. The build is running [here](https://travis-ci.com/github/nengo/keras-lmu/builds/229056913). (EDIT: That's funny... it wouldn't start a build when I pushed to Nani's branch, but when the build passed on the copy that I pushed to `origin`, Github was able to identify that a build passed on the same commit and update the check badges below.)

2021-06-15 15:50 UTC, drasmuss requested changes
Just some minor comments below, looks good overall!

2021-06-15 15:50 UTC, drasmuss commented on CHANGES.rst
> +  and the sequence length (second input dimension) is specified (not ``None``). (`#40`_)
The second part of this isn't new, so I would just have "now supports memory_d > 1" in the changelog.

2021-06-15 15:50 UTC, drasmuss commented on keras_lmu/layers.py
> +        Whether the LMUCell has a (dense) kernel mapping inputs to memory vectors.
I think we could reuse the `kernel_initializer` for this instead of adding a new parameter (i.e. `kernel_initializer=None` would be `has_input_kernel=False`).

2021-06-15 17:37 UTC, hunse commented on keras_lmu/layers.py
> +        Whether the LMUCell has a (dense) kernel mapping inputs to memory vectors.
I was wondering about that, but it seemed less clear to me. We often use `None` to indicate using a default. That said, of course we'll document it, so hopefully we can make it clear. I don't have a strong opinion either way.

2021-06-15 17:41 UTC, hunse commented on CHANGES.rst
> +  and the sequence length (second input dimension) is specified (not ``None``). (`#40`_)
We used to also have the restriction that we didn't use it if `memory_d != 1` (obviously), so I was trying to indicate that that restriction is now gone (and that this will also change how `LMU` is working internally in some cases). Maybe that's not something most users care about, though, so perhaps we don't need to indicate that at all.

2021-06-15 19:06 UTC, drasmuss commented on CHANGES.rst
> +  and the sequence length (second input dimension) is specified (not ``None``). (`#40`_)
Yeah we could note that in the changelog (keras_lmu.LMU will now use the FFT implementation for memory_d > 1). I'd just state it explicitly like that rather than implicity (by not including the memory_d in the list of conditions here).

2021-06-15 19:16 UTC, drasmuss commented on keras_lmu/layers.py
> +        Whether the LMUCell has a (dense) kernel mapping inputs to memory vectors.
We've just got a lot of init parameters for this class already, so I'm inclined to try to avoid adding any more unless we really need to. And from a brief glance at the TF documentation, it seems like layers always use an explicit value for the initializer defaults, none of them are using `None` with an internal default, so hopefully that won't be too confusing to anyone.

2021-06-15 20:08 UTC, hunse commented
OK, I've addressed your comments @drasmuss.

I also noticed that `test_multivariate_lmu` was failing on my machine, though it appears unrelated to these changes (it also failed on master for me); upping the tolerances a hair fixed it for me. (I tried explicitly setting all the dtypes to float32, since it seems like it might be some sort of typing issue, but that didn't fix it. :shrug:)

2021-06-16 13:42 UTC, drasmuss approved these changes
LGTM

2021-06-16 14:23 UTC, merged