WIP: Perform LMUFFT with raw convolution
nengo/keras-lmu pull request #42
Opened 2021-06-15 16:11 UTC by hunse

Add the ability to run the impulse response convolution as a raw convolution, rather than using the FFT. In practice, I've found that this can speed things up, though it also appears to require more CPU memory (which is surprising).

I also added a profiling test.

Based on #40.

TODO:
- [ ] Figure out why this uses more CPU memory in some of our larger models (I have an example)
- [ ] Have the profiling test assert something, or make it an optional test/benchmark
- [ ] Look into using shorter impulse responses when we have shorter theta. This is where this approach could really shine.

2021-07-06 19:45 UTC, hunse commented
When testing this on my RTX 3060 for my specific model, I'm finding that the FFT implementation is faster than the raw conv implementation. So which one is best does seem to depend on the specific hardware/CUDA/TensorFlow. I'm hoping to test across more hardware soon, but I think for the foreseeable future, we're looking at keeping both implementations around. The best would be to autotune it, but that's probably a good chunk more work.

2021-07-14 19:45 UTC, hunse commented
I think this is ready to go. In the end, I had to add two ways of doing the raw convolution, since the one that's faster on GPUs (using NCHW format) doesn't work on CPU.

2021-07-19 17:58 UTC, arvoelke requested changes
Should add a changelog entry too.

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/layers.py
> +                conv_mode=self.conv_mode,
Missing `truncate_ir`.

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/layers.py
> +            raise NotImplementedError(f"Unimplemented conv mode '{self.conv_mode}'")
Nit: I think `raise ValueError(f"Unknown conv mode '{self.conv_mode}'")` may be more typical in situations like this where it's not like there's a known implementation that is clearly missing and could be added right now. Instead we just don't know what to do and don't necessarily plan on supporting/implemented it. An example in scipy for what it's worth: https://github.com/scipy/scipy/blob/v1.7.0/scipy/signal/lti_conversion.py#L530

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/layers.py
> +        (see ``conv_mode``). This is an approximate upper bound on the error relative
or when using `"raw_nchw"` mode

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/layers.py
> +                self.impulse_response = self.impulse_response[: -(i + 1)]
It was a bit confusing to me that this only has an effect for `raw[_nchw]` mode, but the default behaviour is for it to always happen (since the default value of `truncate_ir` is not None). I assume it's not that expensive so not really a big deal, so maybe a comment somewhere here just saying
```
# self.impulse_response is only used when conv_mode != "fft"
```
would help reinforce understanding.

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/layers.py
> +        ordering that is typically faster than "raw" on GPUs, but unsupported on CPUs.
Does it throw a reasonable error message if using `raw_nchw` on the CPU?

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/tests/test_benchmarks.py
> +    elif mode in ("fft", "raw", "raw_nchw"):
Should `raw_nchw` be one of the possible modes for this test? It is `@pytest.mark.parametrize("mode", ["rnn", "fft", "raw"])` above.

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/tests/test_layers.py
> +@pytest.mark.parametrize("conv_mode", ("fft", "raw"))
Can `raw_nchw` be tested here too if the GPU is enabled?

2021-07-19 17:58 UTC, arvoelke commented on keras_lmu/tests/test_benchmarks.py
> +        print(f"step time: {step_time:0.3f}")
I noticed this doesn't have any assert statements anywhere. It also looks to me like it doesn't add any additional coverage. Is there a way to turn it into more of a test, and also how long does it take to run?

2021-07-19 20:04 UTC, hunse commented on keras_lmu/tests/test_benchmarks.py
> +        print(f"step time: {step_time:0.3f}")
Yeah, that was one of the TODOs, but I haven't thought of what to assert yet. NengoDL does something like this and asserts that execution times fall within an expected range for the specific hardware that the TravisCI tests run on, acting as a regression test for performance. However, this repo isn't set up for running TravisCI GPU tests yet, and the tests are slow on CPU (hence the `skipif`). Once this repo has GPU tests, then I'd recommend adding those asserts, but I don't think it makes a lot of sense now. (We could make the tests smaller to run faster on CPU,  and add asserts for that, but ultimately it's GPU performance that we care more about.)

2021-07-21 18:32 UTC, hunse commented on keras_lmu/layers.py
> +                self.impulse_response = self.impulse_response[: -(i + 1)]
I made this truncation only happen if `conv_mode != "fft"`, so that `impulse_response_fft` is always the FFT of impulse response.

2021-07-21 18:35 UTC, hunse commented on keras_lmu/layers.py
> +        ordering that is typically faster than "raw" on GPUs, but unsupported on CPUs.
```
E   tensorflow.python.framework.errors_impl.UnimplementedError: The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW [Op:Conv2D]
```
It's not bad.

2021-07-21 20:57 UTC, arvoelke commented on keras_lmu/layers.py
> +            raise ValueError(f"Unrecognized conv mode '{self.conv_mode}'")
Codecov failure is due to this line.

2021-07-21 20:57 UTC, arvoelke approved these changes
LGTM. I left the one comment about the benchmarks still open for when the next reviewer takes a look. It'll also need a changelog entry, and the codecov failure resolved, but it looks good to me.

2021-07-21 20:59 UTC, arvoelke commented on keras_lmu/tests/test_benchmarks.py
> +        print(f"step time: {step_time:0.3f}")
Ah I forgot TravisCI isn't using the GPU. I think it makes sense to keep this as is for now and remember to come back to it later.

2021-07-22 18:11 UTC, hunse commented on keras_lmu/layers.py
> +            raise ValueError(f"Unrecognized conv mode '{self.conv_mode}'")
I don't understand how this line is not being hit. I added an explicit check for it in `test_validation_errors`. That test is being run and passes (both locally and on TravisCI). There's no way that it should pass if the line's not being hit. Codecov error perhaps?

2021-07-26 18:55 UTC, drasmuss commented on keras_lmu/tests/test_benchmarks.py
> +        print(f"step time: {step_time:0.3f}")
We already run the docs/examples builds on GPU, so we might as well move the test build to the GPU as well. Otherwise I suspect this test will be run rarely/never.

2021-07-27 15:53 UTC, drasmuss commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
I was able to see a performance difference by making the benchmark a bit more compute intensive. But I think the difference was more to do with the other reshapes/transposes going on (which are different in the two conditions), rather than the actual convolution. I pushed a fixup that simplifies the `raw` implementation a bit, and on my machine `raw` is now faster than `raw_nchw`. It'd be good to check what results you see on your machine though.

2021-07-30 14:16 UTC, hunse commented on keras_lmu/layers.py
>      def __init__(
Yeah, I was going to keep it the same for backwards compatibility, particularly since the new implementations are functionally equivalent. But I'm OK to rename it. What about `LMUFF` for "LMU Feed-Forward", since that's the most important difference to me: it's feed-forward, not recurrent? Also conveniently similar to LMUFFT :) The fact that it uses the impulse response might be a bit esoteric for people not so familiar with dynamical systems, so I'm not sure if it'd be as memorable.

2021-07-30 14:26 UTC, hunse commented on keras_lmu/tests/test_benchmarks.py
> +    step_time = np.mean(steptimes.batch_times[1:])
Not all the batches are doing exactly the same thing; for example, the first batch is much longer because there's a lot of overhead, that's why I drop it. I'm not sure if other batches have much overhead, but we'd lose that by doing `min`. Maybe that's not a problem, or maybe it's even a good thing, since it would get at the time of the underlying computation better, which is what we really care about. (Assuming that there would be no differences in overhead between the implementations.)

My only other question is whether each batch is fully synchronous (i.e. whether the whole computation has to be finished before `on_batch_end` is called). I think that this should be the case, but it's the only other way I can think of there being a problem with `min`.

Anyway, I'm fine to make the change, and it should become apparent pretty quickly if there are any problems. (i.e. if the qualitative results from `min` don't agree with `mean`)

2021-08-11 16:47 UTC, hunse commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
The changes definitely make "raw" faster for me. I still see "raw_nchw" as slightly faster, but it's pretty minor. Interestingly, I'm now seeing the base "rnn" implementation as faster than both the "raw" implementations (and "fft" is even faster). Note: I had to drop the batch size to 16 since my GPU wasn't large enough to run with 32.

In light of these changes, I decided to re-test having the signal along the "H" dimension, and it's way faster for me. Double check that it's the same for you, but it removes the transposes, so makes sense that it's faster.

2021-08-11 17:54 UTC, drasmuss commented on keras_lmu/layers.py
> +            u = tf.expand_dims(u, 1)
I don't think this gives the correct output (the axes don't end up in the right order unless you combine batch and memory_d). `test_fft` is failing after this change.

2021-08-11 17:56 UTC, drasmuss commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
The H convolution is still dramatically slower for me (>10x).

2021-08-11 18:28 UTC, hunse commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
Wow, that's super weird that it's such a big difference. I guess it's either to do with GPU, or with CUDA/CuDNN/Tensorflow versions. That's annoying...

2021-08-11 18:41 UTC, hunse commented on keras_lmu/layers.py
> +            u = tf.expand_dims(u, 1)
Ahh, yeah, you're right, it flips the order and memory_d dimensions; it works if you move the transpose on the output before the reshape, but I'm finding that that's significantly slower.

2021-08-12 00:06 UTC, hunse commented on keras_lmu/layers.py
> +            u = tf.expand_dims(u, 1)
OK, pushed a fix for this. Also rebased this all onto master.

2021-08-12 19:50 UTC, drasmuss commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
Fixed the slowdown I was seeing by upgrading cuda/cudnn, now I see `H` as faster same as you, so that's good news.

I'm kind of inclined to just get rid of the `raw_nchw` option. Dropping it would simplify the code and the user interface (and remove any potential GPU/CPU compatibility issues). I increased the number of steps in the benchmark locally to reduce any noise, and I very consistently see `raw` being as fast or faster than `raw_nchw` now.

2021-08-13 14:13 UTC, drasmuss commented on keras_lmu/layers.py
>      def __init__(
I just went with the full `LMUFeedforward`, figured it's not unreasonably long and `LMUFFT/LMUFF` is a lot of capital letters.

2021-08-13 14:51 UTC, drasmuss commented on keras_lmu/layers.py
> +            raise ValueError(f"Unrecognized conv mode '{self.conv_mode}'")
It wasn't being hit because the `call` method is called inside a wrapped `@tf.function` graph, which happens outside the regular python process so it doesn't get picked up by coverage. I moved the validation check to `__init__` instead.

2021-08-13 16:17 UTC, hunse commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
Yeah, I've maybe seen one or two cases where `nchw` is marginally faster, but it's pretty marginal, and plain "raw" is often as fast or faster for me as well. I'd be fine to remove it.

2021-08-13 16:19 UTC, hunse commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
Out of curiosity, about what percentage speedup did you see between W and H? One of my GPUs showed about a 1.5x speedup (old time / new time), but the other showed no speedup.

2021-08-13 16:22 UTC, hunse commented on keras_lmu/tests/test_benchmarks.py
> +    [("rnn", 0.3, 0.4), ("fft", 0.02, 0.03), ("raw", 0.2, 0.3)],
Maybe just note somewhere what kind of GPU these come from (is it a K80 that we use on Azure?)

2021-08-13 16:23 UTC, hunse commented
Fixups look good to me. When you've got all the tests passing, feel free to merge.

2021-08-16 13:30 UTC, drasmuss commented on keras_lmu/layers.py
> +    conv_mode : "fft" or "raw" or "raw_nchw"
It was relatively minor but consistent, on the order of a 10% speedup.

2021-08-16 14:00 UTC, tbekolay commented
New commits lgtm :+1:

2021-08-16 14:45 UTC, merged